<!-- start hide from old browsers;
var loaded = false;

if (parent.frames[0] == null) { window.location = 'https://www.mellon.com/'; }
function ping(){alert("pinged jslib successfully");}
function ReportError(a){alert(a);}
function isEmpty(a){var b=typeof(a);if(b=='object'){if(a==null){b='null';}}var c=((b=='null')||(b=='undefined')||((b=='string')&&(a=='')));return c;}
function isDigits(a){for(var b=0;b<a.length;b++){var c=a.charAt(b);if((c<"0")||(c>"9")){return false;}}return true;}
function isAlpha(a){for(var b=0;b<a.length;b++){var c=a.charAt(b);if(((c<"a")||(c>"z"))&&((c<"A")||(c>"Z"))){return false;}}return true;}
function isAlphaNum(a){for(var b=0;b<a.length;b++){var c=a.charAt(b);if(((c<"a")||(c>"z"))&&((c<"A")||(c>"Z"))&&((c<"0")||(c>"9"))){return false;}}return true;}
function isAlphaNumSpace(a){for(var b=0;b<a.length;b++){var c=a.charAt(b);if(((c<"a")||(c>"z"))&&((c<"A")||(c>"Z"))&&((c<"0")||(c>"9"))&&(c!=" ")){return false;}}return true;}
function isEmail(a){var b=false;for(var c=0;c<a.length;c++){var d=a.charAt(c);if(((d<"a")||(d>"z"))&&((d<"A")||(d>"Z"))&&((d<"0")||(d>"9"))&&(d!="@")&&(d!="-")&&(d!="_")&&(d!=".")){return "BAD CHAR";}if(d=="@"){
if(b){ return "DOUBLE @"; }else { b=true; }}}if(!b){return "NO @";}return "OK";}function hasText(a){a=strip(a," ");return (a!="");}
function strip(a,b){var c=0;while((a.charAt(c)==b)&&(c<a.length)){c++;}var d=a.length;while((a.charAt(d-1)==b)&&(d>0)){d--;}if(d<=c){return "";}else {return a.substring(c,d);}}
function stripLeading(a,b){var c=0;while((a.charAt(c)==b)&&(c<a.length)){c++;}var d=a.length;if(d<=c){return "";}else {return a.substring(c,d);}}
function remove(a,b){var c="";for(var d=0;d<a.length;d++){var e=a.charAt(d);if(b.indexOf(e)==-1){c+=e;}}return c;}
function removeAllBut(a,b){var c="";for(var d=0;d<a.length;d++){var e=a.charAt(d);if(b.indexOf(e)!=-1){c+=e;}}return c;}
function isComposedOf(a,b){for(var c=0;c<a.length;c++){if(b.indexOf(a.charAt(c))==-1){return false;}}return true;}
function indexOfFirstIn(a,b){for(var c=0;c<a.length;c++){if(b.indexOf(a.charAt(c))!=-1){return c;}}return -1;}
function indexOfFirstNotIn(a,b){for(var c=0;c<a.length;c++){if(b.indexOf(a.charAt(c))==-1){return c;}}return -1;}
function isValidText(a,b){if(isEmpty(b)){b="Please enter a value.";}if((a.indexOf("<")!=-1)||(a.indexOf(">")!=-1)||(a.indexOf(";")!=-1)){ReportError(b+" Your input cannot contain \">\", \"<\", or \";\".");return "";}a=strip(a," ");
if(a==""){ReportError(b);}return a;}function isValidStockSymbol(a,b){var c="ABCDEFGHIJKLMNOPQRSTUVWXYZ^";if(isEmpty(b)){b="Please enter a value.";}a=strip(a," ");if(a==""){ReportError(b);return "";}a=a.toUpperCase();if(a.length>6){ReportError(b+" Your input may not be longer than 6 letters.");
return "";}for(i=0;i<a.length;i++){if(c.indexOf(a.charAt(i))<0){ReportError(b+" Your input may contain only letters or the ^ symbol.");return "";}}return a;}function isValidDateString(a,b){if(isEmpty(b)){b="Please enter a valid date.";}var c=indexOfFirstNotIn(a,"0123456789");if(c==-1){var d=a.charAt(c);ReportError(b+" \n\nEnter dates in a mm/dd/yy, mm-dd-yy,"+" mm/dd/yyyy or mm-dd-yyyy format.");
return "";}else {var d=a.charAt(c);d=a.charAt(c);if(d!='-'&&d!='/'){ReportError(b+" \n\nUse the - or / character "+"in between the month, day and year digits.");return "";}var f=a.indexOf(d,c+1);
var g="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";if((f==-1)||(g.indexOf(d)!=-1)){ReportError(b+" You must have two matching non-alphanumeric separators.");return "";}var h=a.substring(0,c);
var i=a.substring(c+1,f);var j=a.substring(f+1,a.length);if((j.length!=2)&&(j.length!=4)){ReportError(b+". Year must be entered as 2 or 4 digits.");return "";}if(!isDigits(h+i+j)){ReportError(b+" All non-d characters must be numbers.");
return "";}}h=parseInt(h,10);var k=parseInt(i,10);j=parseInt(j,10);if(j<70){j+=2000;}else {if((j>=70)&&(j<100)){j+=1900;}else {if(j<1000){ReportError(b+" Enter either a two-digit or a four-digit year.");
return "";}else {if(j<1900){ReportError(b+" Enter a date since 1900.");return "";}}}}if((h<1)||(h>12)){ReportError(b+" The month must be between 1 and 12.");return "";}var l=new Array(12);
l[1]=31;l[2]=28;l[3]=31;l[4]=30;l[5]=31;l[6]=30;l[7]=31;l[8]=31;l[9]=30;l[10]=31;l[11]=30;l[12]=31;if(((j%4==0)&&(j%100!=0))||(j%400==0)){l[2]=29;}if((k<1)||(k>l[h])){ReportError(b+" This month has only "+l[h]+" days.");
return "";}i=i+"";h=h+"";j=j+"";if(i.length<2){i="0"+i;}if(h.length<2){h="0"+h;}return h+"/"+i+"/"+j;}function getTodayDate(a,b,c){var d=c;var e=a;var f=b;if(e<10){e="0"+e;}if(f<10){f="0"+f;}return (e+"/"+f+"/"+d);}
function dateCompare(a,b,c){var d=a.substring(0,2);var e=a.substring(3,5);var f=a.substring(6,10);var g=b.substring(0,2);var h=b.substring(3,5);var i=b.substring(6,10);var j=d+e+f+g+h+i;if(!isDigits(j)||(j.length!=16)){
ReportError("Developers! Please call isValidDateString() first!");return false;}d=parseInt(d,10);e=parseInt(e,10);f=parseInt(f,10);g=parseInt(g,10);h=parseInt(h,10);i=parseInt(i,10);if(c.charAt(0)=="="){
return ((f==i)&&(d==g)&&(e==h));}var k="((f "+c+" i) ||\n"+"((f == i) && (d "+c+" g)) ||\n"+"((f == i) && (d == g) && (e "+c+" h)))";return (eval(k));}function isValidDateRange(a,b,c){if(isEmpty(c)){c="The first date in the range must be less than the second.";}if(isEmpty(a)||isEmpty(b)){ReportError("Please enter both date values in the range, or neither.");return false;}if(dateCompare(b,a,"<")){
ReportError(c);return false;}else {return true;}}function isValidPastDate(a,b,c,d,e){if(isEmpty(e)){e="Please enter a valid past date.";}if(dateCompare(d,getTodayDate(a,b,c),"<")){return d;}else {ReportError(e);return "";}}
function isValidPresentDate(a,b,c,d,e){if(isEmpty(e)){e="Please enter a valid present date.";}if(dateCompare(d,getTodayDate(a,b,c),"==")){return d;}else {ReportError(e);return "";}}
function isValidFutureDate(a,b,c,d,e){if(isEmpty(e)){e="Please enter a valid future date.";}if(dateCompare(d,getTodayDate(a,b,c),">")){return d;}else {ReportError(e);return "";}}
function isValidNonPastDate(a,b,c,d,e){if(isEmpty(e)){e="Please enter a valid present or future date.";}if(dateCompare(d,getTodayDate(a,b,c),"<")){ReportError(e);return "";}else {return d;}}
function isValidNonPresentDate(a,b,c,d,e){if(isEmpty(e)){e="Please enter a valid past or future date.";}if(dateCompare(d,getTodayDate(a,b,c),"==")){ReportError(e);return "";}else {return d;}}
function isValidNonFutureDate(a,b,c,d,e){if(isEmpty(e)){e="Please enter a valid past or present date.";}if(dateCompare(d,getTodayDate(a,b,c),">")){ReportError(e);return "";}else {return d;}}
function isNextMonth(a,b,c,d,e){if(isEmpty(e)){e="Please enter a date within the next month.";}var f=d.substring(0,2);var g=d.substring(3,5);var h=d.substring(6,10);var i=parseInt(f,10);g=parseInt(g,10);h=parseInt(h,10);var j=a+1;
if(j==13){j=1;c=c+1;}if(h!=c){if(((c-h)==1)&&(i==12)&&(j==1)&&(g>=b))return d;else {ReportError(e);return "";}}else {if(i==a&&g>=b){return d;}else {if(i==j&&g<=b){return d;}else {
ReportError(e);return "";}}}}function isValidDollar(a,b){if(isEmpty(b)){b="Please enter a valid dollar amount.";}a=strip(a,"$");a=remove(a,",");if(!isComposedOf(a,".0123456789")){ReportError(b+" Your input must contain only \"$\", "+"commas, decimal points, and digits.");
return "";}var c=a.indexOf(".");if(c!=a.lastIndexOf(".")){ReportError(b+" You may not have more than one decimal point.");return "";}if(c==-1){ReportError(b+" You must enter a decimal point and cents.");
return "";}else {if(c==0){var d="0";var e=a.substring(1,a.length);}else {if(c==(a.length-1)){ ReportError(b+" You must enter cents after the decimal point."); return "";}else {var d=a.substring(0,c);
var e=a.substring(c+1,a.length);}}}if(e.length>2){ReportError(b+" You cannot enter more than two decimal places.");return "";}if(e.length==1){ReportError(b+" You must enter cents after the decimal point.");
return "";}d=stripLeading(d,"0");if(d.length==0){d="0";}return "$"+d+"."+e;}function isValidDollarRange(a,b,c){if(isEmpty(c)){c="The first dollar value in the range must be less than "+"the second.";}if(isEmpty(a)||isEmpty(b)){ReportError("Please enter both dollar values in the range, or neither.");return false;
}a=remove(a,"$,");b=remove(b,"$,");if(!isComposedOf(a+b,"0123456789.")){ReportError("Developers! Call isValidDollar first!");return false;}if(parseFloat(a,10)<=parseFloat(b,10)){return true;
}else {ReportError(c);return false;}}function isValidDollarRangeBetween(a,b,c){if(isEmpty(c)){c="The first dollar value in the range must be less than "+"the second.";}if(isEmpty(a)||isEmpty(b)){ReportError("Please enter both dollar values in the range, or neither.");return false;
}a=remove(a,"$,");b=remove(b,"$,");if(!isComposedOf(a+b,"0123456789.")){ReportError("Developers! Call isValidDollar first!");return false;}if(parseFloat(a,10)<parseFloat(b,10)){return true;}else {
ReportError(c);return false;}}function isValidNotEqual(a,b,c){if(isEmpty(c)){c="The two fields may not be equal.";}if(a==b){ReportError(c);return false;}else {return true;}}
function isValidAlpha(a,b){if(isEmpty(b)){b="Please enter alphabetic input.";}if(isAlpha(a)){return a;}else {ReportError(b+" Your input must contain only alphabetic characters.");return "";}}
function isValidNumber(a,b){if(isEmpty(b)){b="Please enter a valid number.";}if(isDigits(a)){return a;}else {ReportError(b+" Your input must contain only numeric digits.");return "";}}
function isValidAlphaNum(a,b){if(isEmpty(b)){b="Please enter alphanumeric input.";}if(isAlphaNum(a)){return a;}else {ReportError(b+" Your input must contain only alphanumeric digits.");return "";}}
function isValidAlphaNumSpace(a,b){if(isEmpty(b)){b="Please enter alphanumeric or space characters.";}if(isAlphaNumSpace(a)){return a;}else {ReportError(b+" Your input must contain only alphanumeric or space characters.");return "";
}}function isValidEmail(a,b){if(isEmpty(b)){b="Please enter email input.";}var c=isEmail(a);if(c=="OK"){return a;}else if(c=="BAD CHAR"){ReportError(b+" Your input must contain only alphanumeric" +" data, and/or \"@\", \".\", \"_\".");
return "";}else if((c=="DOUBLE @")||(c=="NO @")){ReportError(b+" Your input must contain one and only one" +" \"@\" character.");return "";}}function isValidNumberRange(a,b,c){if(isEmpty(c)){c="The first number in the range must be less than the second.";}if(isEmpty(a)||isEmpty(b)){ReportError("Please enter both numeric values in the range, or neither.");return false;
}if(!isDigits(a+b)){ReportError("Developers! Call isValidNumber first!");}if(parseInt(a,10)<=parseInt(b,10)){return true;}else {ReportError(c);return false;}}function isValidNumberRangeBetween(a,b,c){if(isEmpty(c)){c="The first number in the range must be less than the second.";}if(isEmpty(a)||isEmpty(b)){ReportError("Please enter both numeric values in the range, or neither.");return false;
}if(!isDigits(a+b)){ReportError("Developers! Call isValidNumber first!");}if(parseInt(a,10)<parseInt(b,10)){return true;}else {ReportError(c);return false;}}function isValidOther(a,b,c,d){var e=a.length;if(b==c&&e!=c){ReportError(d+"\n\nThe required length is "+c);return "";}if(e>b){ReportError(d+"\n\nThe maximum length is "+b);return "";}if(e<c){ReportError(d+"\n\nThe minimum length is "+c);
return "";}return a;}function ValidateDate(a,b,c,d,e,f,g){var h=0;var i=1;var j=2;var k=3;var l=4;var m=5;var n=6;var o=7;var p=f.value;var q="";if(hasText(p)){q=isValidText(p,"Please enter a "+e);if(q==""){f.select();f.focus();return false;
}else {f.value=q;p=q;}q=isValidDateString(p,"Please enter a "+e);if(q==""){f.select();f.focus();return false;}else {f.value=q;p=q;}if(parseInt(g,10)==i){q=isValidPastDate(b,c,d,p,
"The "+e+" must be in the past.");if(q==""){f.select();f.focus();return false;}else {f.value=q;p=q;}}else if(parseInt(g,10)==parseInt(j,10)){q=isValidPresentDate(b,c,d,p,"The "+e+" must be today.");
if(q==""){f.select();f.focus();return false;}else {f.value=q;p=q;}}else if(parseInt(g,10)==parseInt(k,10)){q=isValidFutureDate(b,c,d,p,"The "+e+" must be in the future.");if(q==""){f.select();
f.focus();return false;}else {f.value=q;p=q;}}else if(parseInt(g,10)==parseInt(l,10)){q=isValidNonPastDate(b,c,d,p,"The "+e+" must not be in the past.");if(q==""){f.select();f.focus();
return false;}else {f.value=q;p=q;}}else if(parseInt(g,10)==parseInt(m,10)){q=isValidNonPresentDate(b,c,d,p,"The "+e+" cannot be today.");if(q==""){f.select();f.focus();return false;}
else {f.value=q;p=q;}}else if(parseInt(g,10)==parseInt(n,10)){q=isValidNonFutureDate(b,c,d,p,"The "+e+" cannot be in the future.");if(q==""){f.select();f.focus();return false;}else {
f.value=q;p=q;}}else if(parseInt(g,10)==parseInt(o,10)){q=isNextMonth(b,c,d,p,"The "+e+" must be within the next month.");if(q==""){f.select();f.focus();return false;}else {f.value=q;
p=q;}}else {}}else if(a){ReportError(e+" is a required field.");f.focus();return false;}return true;}function ValidateDateRange(a,b,c,d,e){var f=a.value;var g=b.value;if((!hasText(f))&&(!hasText(g)))return true;if((!e)&&(!hasText(g)))return true;if(!isValidDateRange(f,g,"The "+c+" must not be later than the "+d+".")){a.select();
a.focus();return false;}return true;}function ValidateAmount(a,b,c){var d=c.value;var e="";if(hasText(d)){e=isValidText(d,"Please enter the "+b+".");if(e==""){c.select();c.focus();return false;}else {c.value=e;d=e;}e=isValidDollar(d,"Please enter the "+b+".");
if(e==""){c.select();c.focus();return false;}else {c.value=e;d=e;}}else if(a){ReportError(b+" is a required field.");c.focus();return false;}return true;}function ValidateAmountRange(a,b,c,d){var e=a.value;var f=b.value;if(hasText(e+f)){if(!isValidDollarRange(e,f,"The "+c+" must be less than or equal to the "+d+".")){a.select();a.focus();return false;}}return true;}function ValidateNotEqual(a,b,c,d){if(a.type=='select-one'){var e=a.options[a.selectedIndex].value;}else {var e=a.value;}if(b.type=='select-one'){var g=b.options[b.selectedIndex].value;}else {var g=b.value;}if(hasText(e+g)){if(!isValidNotEqual(e,g,
"The "+c+" may not be the same as the "+d+".")){a.select();a.focus();return false;}}return true;}function ValidateCheck(a,b,c){var d=c.value;var e="";if(hasText(d)){e=isValidText(d,"Please enter the "+b+".");if(e==""){c.select();c.focus();return false;}else {c.value=e;d=e;}e=isValidNumber(d,"Please enter the "+b+".");
if(e==""){c.select();c.focus();return false;}else {c.value=e;d=e;}}else if(a){ReportError(b+" is a required field.");c.focus();return false;}return true;}function ValidateCheckRange(a,b,c,d){var e=a.value;var f=b.value;if(hasText(e+f)){if(!isValidNumberRange(e,f,"The "+c+" must be less than or equal to the "+d+".")){a.select();a.focus();return false;}}return true;}function ValidateOther(a,b,c,d,e,f){var g=0;var h=1;var i=2;var j=3;var k=4;var l=c.value;var m="";if(hasText(l)){var n="Please enter a "+b+".";m=isValidText(l,n);if(m==""){c.select();c.focus();return false;}else {c.value=m;
l=m;}m=isValidOther(l,f,e,n);if(m==""){c.select();c.focus();return false;}else {c.value=m;l=m;}if(parseInt(d,10)==parseInt(h,10)){m=isValidAlpha(l,n);}else if(parseInt(d,10)==parseInt(i,10)){
m=isValidNumber(l,n);}else if(parseInt(d,10)==parseInt(j,10)){m=isValidAlphaNum(l,n);}else if(parseInt(d,10)==parseInt(k,10)){m=isValidAlphaNumSpace(l,n);}else {m=l;}if(m==""){c.select();
c.focus();return false;}else {c.value=m;l=m;}}else if(a){ReportError(b+" is a required field.");c.focus();return false;}return true;}function ValidateEmail(a,b,c){var d=c.value;var e="";if(hasText(d)){var f="Please enter a "+b+".";e=isValidText(d,f);if(e==""){c.select(); c.focus(); return false;} else {c.value=e;d=e;}e=isValidEmail(d,f);if(e=="")
{c.select();c.focus();return false;}else {c.value=e;d=e;}}else if(a){ReportError(b+" is a required field.");c.focus();return false;}return true;}function ValidateMNumber(a,b,c,d,e){var f=c.value;var g="";if(hasText(f)){g=isValidText(f,"Please enter the "+b+".");if(g==""){c.select();c.focus();return false;}else {c.value=g;f=g;}g=isValidNumber(f,"Please enter the "+b+".");
if(g==""){c.select();c.focus();return false;}else {c.value=g;f=g;}if((parseInt(f,10)>e)||(parseInt(f,10)<d)){ReportError("Please enter a value between "+d+" and "+e+".");c.select();c.focus();
return false;}}else if(a){ReportError(b+" is a required field.");c.focus();return false;}return true;}function ValidateMNumberRange(a,b,c,d){var e=a.value;var f=b.value;if(hasText(e+f)){if(!isValidNumberRange(e,f,"The "+c+" must be less than or equal to the "+d+".")){a.select();a.focus();return false;}}return true;}function ValidateStockSymbol(a,b,c){var d=c.value;var e="";if(hasText(d)){e=isValidStockSymbol(d,"Please enter the "+b+".");if(e==""){c.select();c.focus();return false;}else {c.value=e;d=e;}}else if(a){ReportError(b+" is a required field.");
c.focus();return false;}return true;}
loaded = true;

// end hide -->
